INSERT INTO brands (id, name,image_url,description)
VALUES (1, 'Nike','https://c.static-nike.com/a/images/w_1920,c_limit/bzl2wmsfh7kgdkufrrjq/image.jpg','Nike is an icon born under the name Blue Ribbon Sports in Oregon, USA, in 1972. Since its establishment until today, the brand has produced sneakers and apparel that push the limits every day. Nike Air Max, Huarache, Air Force or Roshe are just an example of what we offer.'),
       (2,'Adidas', 'https://logos-world.net/wp-content/uploads/2020/04/Adidas-Symbol.png', 'The legacy, history and legend that created the whole culture around sneakers. adidas Originals has been dominating the field of men''s fashion, sneakers and sportswear for decades. Why? Because behind the unceasing progress of the Originals lies proven quality, reliable materials and innovation dressed in the best of the past. Read on to find out why adidas Originals sneakers and shoe wear are so popular today and how they managed to dominate almost all men''s footwear.'),
       (3,'Converse','https://i.pinimg.com/originals/82/47/37/82473738c0e36e463be9de989ace02df.jpg','Converse trainers, Converse sneakers, Converse canvas shoes, or simply Converse - call them however you want, they are the one and only! What is important is that this brand came on the market as early as 1908 as the Converse Rubber Shoe Company, which ranks Converse shoes as sneakers with the longest and, possibly, the richest history.'),
       (4,'Jordan', 'https://i.pinimg.com/222x/a2/bc/bb/a2bcbb216b790eb34844962944a3a16e.jpg','A wide selection of unique shoes and apparel that bear the surname of the most famous basketball player of all time. Michael Jordan joined Nike nearly thirty years ago and Nike has already released dozens of models in hundreds of colors under his auspice.'),
       (5, 'Vans','https://wallpaperaccess.com/full/889590.jpg', 'Van Doren Rubber Co. was established in 1966 by Paul Van Doren in Anaheim, California when he tried to mold soles on a classic waffle maker. For many people, it might have been a bizarre idea at that time but from today''s perspective, it has led to one of the greatest milestones in the production of modern footwear.'),
       (6, 'Puma','https://upload.wikimedia.org/wikipedia/en/thumb/4/49/Puma_AG.svg/1920px-Puma_AG.svg.png', 'When you launch the adidas brand with your brother, but then you have a fall out, try creating the Puma brand. That is exactly how the German brand with the big cat in the emblem was born. Today it is one of the world''s largest manufacturers of clothing and footwear, offering everything from strictly sporty gadgets to purely lifestyle sneakers and clothing. In addition, Puma likes to collaborate with well-known artists so you can add to your shoe collection or wardrobe a piece that has been designed in the hands of singer the Weeknd and Barbarian singer Rihanna.'),
       (7, 'Reebok','https://logos-download.com/wp-content/uploads/2016/02/Reebok_Logo_2019.png', 'Reebok was founded in 1895 in England.It''s a dynamically developing brand. It supports a person''s individuality not only in sports but also in everyday life.The goal of the brand is to offer shoes that fit customers perfectly, are comfortable and cater to their needs. The guarantee of customer satisfaction is modern technology, high quality materials, original colorways and increasingly honed cuts. It''s important for the brand to enjoy your sporting experience and have fun during it.'),
       (8, 'The North Face','https://logos-world.net/wp-content/uploads/2020/11/The-North-Face-Logo.png','The North Face is an American brand dedicated to producing outdoor equipment in extreme conditions. This brand was founded in California in 1968 and today we can buy clothing and footwear not only for sports and hiking, but also for casual wear.');

INSERT INTO clothes(id,name,price,image_url,brand_id,description)
VALUES (1,'Club Tee',18.95,'https://static.footshop.com/445450/37485.jpg',1,'100% Cotton - A very soft and pleasant material whose properties include tensile strength and elongation at break. Unlike other materials, it does not get damaged easily when washed often.'),
       (2, 'Fleece Pullover Hoodie',49.95,'https://static.footshop.com/411985/85273.jpg',1,'80% Cotton - A very soft and pleasant material whose properties include tensile strength and elongation at break. Unlike other materials, it does not get damaged easily when washed often.
20% Polyester - a very strong synthetic fiber that boasts high heat resistance and excellent odor absorption'),
       (3,'Joggers BB',39.95,'https://static.footshop.com/602353/115462.jpg',1,'80% Cotton - A very soft and pleasant material whose properties include tensile strength and elongation at break. Unlike other materials, it does not get damaged easily when washed often.
20% Polyester - a very strong synthetic fiber that boasts high heat resistance and excellent odor absorption'),
       (4,'3-Stripes Crew',42.95,'https://static.footshop.com/585667/127225.jpg',2, 'The temperature dropped, but that doesn''t mean your style has to dip too. Thanks to the heavyweight French terry build and iconic 3-Stripes, this adidas sweatshirt keeps you feeling cosy and looking fresh at the same time. Our cotton products support sustainable cotton farming. This product is also made with recycled content as part of our ambition to end plastic waste.');
